drop table cash_card;
CREATE TABLE cash_card
(
    ID       BIGINT auto_increment PRIMARY KEY,
    AMOUNT   double NOT NULL DEFAULT 0,
    OWNER    VARCHAR(256) NOT NULL
);

INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (102, 200.00, 'kumar2');